name: dasar_flame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flame: ^1.20.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
assets:
- assets/images/ships/
- assets/images/
- assets/images/bullets/
- assets/images/explosion/
- assets/images/items/
- assets/images/mateor/
- assets/images/parallax/
- assets/ships/spaceShips_001.png

uses-material-design: true